[project]
name = "test"
version = "0.1"
description = "test project"


[project.optional-dependencies]
dev = [
  "pytest",
  "coverage",
]


[tool.pytest.ini_options]
testpaths = [
  "tests",
]

addopts = "--verbose"

